version: "3.3"

services:
  elasticsearch:
    image: "elasticsearch:7.2.0"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: "kibana:7.2.0"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  esdata:
    driver: local
